try:
    n = int(input("Enter the number"))
except Exception:
    print("Exception handled")
